@startuml
package App{
    package model{
        class user{
            -name
            -email
        }
    }
    note bottom : php artisan make:filament-resource UserResource --generate
    package migration{
        class Create_User{
            -id
            -name
        }
    }
    note bottom : php artisan make:filament-resource UserResource --generate
    package filament-resource{
        class UserResouce{
            +test
        }
    }
    note bottom : php artisan make:filament-resource UserResource --generate
}
@enduml