@startuml

start

:Login;
:Masukkan Email dan Password;
if (Verifikasi User) then (Berhasil)
    if (Apakah Admin?) then (Ya)
        :Tampilkan Dashboard Admin;
        :Kelola Data Pasien;
        :Kelola Data Pengguna;
        if (Tambah Data Pasien?) then (Ya)
            :Input Data Pasien Baru;
            :Simpan Data;
        endif

        if (Lihat Laporan Data Pasien?) then (Ya)
            :Tampilkan Laporan Pasien;
        endif

    else (Tidak)
        :Tampilkan Dashboard Pengguna;
        if (Pilih Pasien?) then (Ya)
            :Tampilkan Detail Pasien;
            if (Update Data?) then (Ya)
                :Update Data Medis Pasien;
                :Simpan Perubahan;
            endif
        endif
    endif
else (Gagal)
    :Tampilkan Pesan Error;
endif

stop

@enduml
