@startuml usecase

actor "Anggota" as A
actor "Pustakawan bagian Registrasi" as P
actor "Pustakawan bagian buku" as P2


usecase "Registrasi Anggota" as UC1
usecase "Update Data Anggota" as UC2
usecase "ditolak" as UC3
usecase "diterima" as UC4
usecase "Update Data Buku" as UC5
usecase "Menambah Buku" as UC6
usecase "Menghapus Buku" as UC7
usecase "Pengembalian Buku" as UC8
usecase "Meminjam Buku" as UC9
usecase "Melihat Buku" as UC10
usecase "stop" as UC11
usecase "cek buku" as UC12
usecase "tersedia" as UC13
usecase "tidak tersedia" as UC14
usecase "disetujui" as UC15

A -> UC1 : Registrasi
UC1 -> P : Menerima Notifikasi
P -> UC2 : Update Data
UC2 .> UC3 : extend
UC2 .> UC4 : extend
UC3 --> A : Menerima notifikasi
UC4 -> A : Menerima notifikasi
A --> UC11 : jika registrasi ditolak
A --> UC10 : jika registrasi diterima
UC10 --> UC9 : Peminjaman
UC9 --> P2 : Menerima notifikasi

P2 -> UC12 : pengecekan
UC12 .> UC14 : extend
UC14 -> UC11 : stop
UC12 ..> UC13 : extend
UC13 -> UC15 : disetujui
UC15 -> UC8 : memberitahukan jadwal pengembalian

P2 --> UC5 : Update Data
UC5 ..> UC6 : include
UC5 ..> UC7 : include










@enduml